# Generated by Django 2.1.2 on 2018-10-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('DOB', models.DateField(null=True)),
                ('Phone_Number', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
